tazama-lf/transaction-aggregation-decisioning-processor

src/classes/alert.ts
src/controllers/execute.ts

Better placement of prcgTmCRSP and prcgDP

fix: moving of prcgTmCRSP and prcgDP to alert root

---

src/classes/alert.ts
src/controllers/execute.ts

Related to https://github.com/frmscoe/General-Issues/issues/153

fix: correct prcgTm for data prep

---

src/services/logic.service.ts

return nanoseconds only to the field
Related to https://github.com/frmscoe/General-Issues/issues/67 as (BUG FIX)
Gist: after finding out that the milliseconds would be ununiform with the precision of decimals we decided to just use nanoseconds

fix: return nanoseconds for elapsed time

---

jest.config.ts
src/interfaces/metaData.ts
src/services/logic.service.ts

Related to: https://github.com/rtkay123/channel-/General-Issues/issues/178

feat: utilise traceParent from services in chain

---

jest.config.ts
package-lock.json
package.json
src/apm.ts
src/index.ts
src/services/logic.service.ts

Related to: https://github.com/frmscoe/General-Issues/issues/178

fix: auto spans for supporteed technologies

---

.env.template
Dockerfile
src/config.ts

Related to https://github.com/frmscoe/General-Issues/issues/225

fix: update Dockerfile with FQDN for apm

---

__tests__/unit/logic.test.ts
package-lock.json
package.json
src/services/logic.service.ts

In Relation to: https://github.com/frmscoe/General-Issues/issues/231
Tested on Sandbox 1.

Redis lookup enhancement

---

package-lock.json
package.json
src/apm.ts
src/services/logic.service.ts

Related to: https://github.com/frmscoe/General-Issues/issues/238

refactor: use lib apm service

---

src/services/logic.service.ts

fixes: https://github.com/frmscoe/General-Issues/issues/251

Fix duplicate channel processing bug

---

__tests__/unit/logic.test.ts
package-lock.json
package.json
src/index.ts
src/services/logic.service.ts

Related to https://github.com/frmscoe/General-Issues/issues/265

Protobuf redis

---

__tests__/unit/logic.test.ts
package-lock.json
package.json

chore: update package version

---

__tests__/unit/logic.test.ts
package-lock.json
package.json
src/index.ts
src/services/helper.service.ts
src/services/logic.service.ts

Related to https://github.com/frmscoe/General-Issues/issues/265
Already Implemented but was efficient enough 
Had to remove fastJson serialization completely

fix: protobuf data transaction with redis

---

__tests__/unit/logic.test.ts
src/index.ts

Related: https://github.com/frmscoe/General-Issues/issues/277

Standardize db manager startup

---

package-lock.json
package.json

Related to https://github.com/frmscoe/General-Issues/issues/287

chore: bump up version of libs

---

__tests__/unit/logic.test.ts
package-lock.json
package.json

Related to: https://github.com/frmscoe/General-Issues/issues/281

Remove `desc` from rule and typology results

---

.dockerignore
.editorconfig
.env.template
.eslintignore
.eslintrc.js
.gitignore
.npmrc
.prettierignore
.sonarcloud.properties
__tests__/__mocks__/arango.js
__tests__/__mocks__/ioredis.js
__tests__/unit/logic.test.ts
cluster-setup.ts
deployment.yaml
docker-compose.yaml
jest.config.ts
service.yaml
src/apm.ts
src/config.ts
src/index.ts
src/interfaces/iPain001/GrpHdr.ts
src/interfaces/iPain001/PmtInf/CdtTrfTxInf.ts
src/interfaces/iPain001/PmtInf/index.ts
src/interfaces/iPain001/SplmtryData.ts
src/interfaces/iPain001/index.ts
src/interfaces/iTypologyExpression.ts
src/interfaces/metaData.ts
src/services/helper.service.ts
src/services/logic.service.ts
src/services/services.ts

Related to https://github.com/frmscoe/General-Issues/issues/115

Add licensing

---

__tests__/unit/logic.test.ts
jest.config.ts
package-lock.json
package.json
src/services/helper.service.ts
src/services/logic.service.ts

In Relation to : https://github.com/frmscoe/General-Issues/issues/15

Feat thresholds

---

.github/workflows/milestone.yml
.github/workflows/release.yml
Dockerfile
package.json

chore: Bump version for release

---

__tests__/unit/channel.helper.test.ts
package-lock.json
package.json

chore(deps): update prettier

---

README.md

Updated the mermaid diagram in the readme to reflect current processor functionality

docs: update mermaid flow diagram

---

.github/workflows/milestone.yml
.github/workflows/release.yml

fix: Reference main branch for release

---

package-lock.json
package.json

build: update lib versions

---

.github/workflows/node.js.yml

build: update dependencies

---

Dockerfile
src/services/logic.service.ts

Fixed log argument
Added transaction complete log

fix: use typology cfg and add completion log

---

.github/workflows/milestone.yml
.github/workflows/node.js.yml
.github/workflows/release.yml
.npmrc
__tests__/unit/logic.service.test.ts
__tests__/unit/typology.helper.test.ts
package-lock.json
package.json
src/apm.ts
src/config.ts
src/index.ts
src/services/helper.service.ts
src/services/logic.service.ts
src/services/services.ts

- Upgrade library to include efrup workflow proto file
- Migrate to new org
Add serialize/deserializing of proto file with efrup workfile properties

feat: add efrup library functonality

---

package-lock.json
package.json

build: remove unused deps

---

__tests__/unit/typology.helper.test.ts
package-lock.json
package.json

- Updated the library versions
- Fixed outstanding tests
- To Facilitate communication between processors using the new data cache.
- Improve code coverage

feat: Multi currency

---

package-lock.json
src/services/logic.service.ts

Write datacache in evaluationResults
#271

feat: write dataCache to evaluation results

---

package-lock.json
package.json

Updated version
Updated dependencies for frms-coe-lib (5.1.1) and frms-coe-startup-lib (2.4.1)
Release 2.2.0

Release prep 2 2 0
